-- AlterTable
ALTER TABLE "User" ADD COLUMN     "aiRequestsToday" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "dailyAiLimit" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "lastAiRequestAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
