export interface SubtitleCue {
    start: number;
    duration: number;
    text: string;
}

export interface CaptionTrack {
    baseUrl: string;
    kind?: string;
    vssId?: string;
    languageCode: string;
    name?: {
        simpleText?: string;
    };
}

export interface PlayerResponse {
    captions?: {
        playerCaptionsTracklistRenderer?: {
            captionTracks?: CaptionTrack[];
        };
    };
}

export class YouTubeTranscriptFetcher {
    /**
     * Public orchestrator to fetch and parse the YouTube video transcript.
     * Conforms to the Facade and Single Responsibility Principles.
     */
    static async fetchTranscript(videoId: string, preferredLang: string = 'Auto'): Promise<SubtitleCue[]> {
        try {
            const html = await this.fetchHtml(videoId);
            const playerResponse = this.extractPlayerResponse(html);
            const captionTracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
            
            if (!captionTracks || captionTracks.length === 0) return [];

            const track = this.selectBestTrack(captionTracks, preferredLang);
            if (!track || !track.baseUrl) return [];

            const xmlText = await this.fetchXml(track.baseUrl);
            const isAutoGenerated = this.isTrackAutoGenerated(track);
            const rawCues = this.parseXmlToCues(xmlText, isAutoGenerated);

            return this.mergeAndCleanCues(rawCues, isAutoGenerated);
        } catch (error) {
            console.error('Failed to fetch YouTube transcript:', error);
            return [];
        }
    }

    static cleanSubtitleText(text: string): string {
        return text
            .replace(/([a-zA-Z-áéíóúÁÉÍÓÚñÑ]+\s*)?\((auto-generated|generado automáticamente)\)/gi, '')
            .replace(/click[\s\S]*?for[\s\S]*?settings/gi, '')
            .replace(/haz\s*clic\s*para\s*ver\s*las\s*opciones/gi, '')
            .replace(/\[.*?\]/g, '')
            .replace(/\(.*?\)/g, '')
            .trim();
    }

    private static async fetchHtml(videoId: string): Promise<string> {
        const response = await fetch(`https://www.youtube.com/watch?v=${videoId}`);
        return response.text();
    }

    private static async fetchXml(baseUrl: string): Promise<string> {
        const response = await fetch(baseUrl);
        return response.text();
    }

    /**
     * Extracts the ytInitialPlayerResponse configuration JSON object from watch page HTML.
     */
    private static extractPlayerResponse(html: string): PlayerResponse | null {
        const startStr = 'ytInitialPlayerResponse = ';
        const startIdx = html.indexOf(startStr);
        if (startIdx === -1) return null;
        
        const start = html.indexOf('{', startIdx);
        if (start === -1) return null;

        let braceCount = 0;
        let endIdx = -1;
        for (let i = start; i < html.length; i++) {
            if (html[i] === '{') braceCount++;
            else if (html[i] === '}') braceCount--;
            if (braceCount === 0) {
                endIdx = i;
                break;
            }
        }
        if (endIdx === -1) return null;

        const jsonStr = html.substring(start, endIdx + 1);
        return JSON.parse(jsonStr) as PlayerResponse;
    }

    /**
     * Selects the most appropriate subtitle track based on preferred language.
     * Prioritizes manual tracks over auto-generated ones.
     */
    private static selectBestTrack(captionTracks: CaptionTrack[], preferredLang: string): CaptionTrack | null {
        const lowerPref = preferredLang.toLowerCase();
        let track: CaptionTrack | null = null;

        if (preferredLang !== 'Auto') {
            const matchesPref = (t: CaptionTrack) =>
                !!(t.name?.simpleText?.toLowerCase().includes(lowerPref) ||
                   t.languageCode.toLowerCase() === lowerPref.substring(0, 2));

            // 1. Preferred manual track
            track = captionTracks.find((t) => matchesPref(t) && !this.isTrackAutoGenerated(t)) || null;
            
            // 2. Preferred auto-generated track
            if (!track) {
                track = captionTracks.find((t) => matchesPref(t)) || null;
            }
        }

        // 3. Fallback to any manual track
        if (!track) {
            track = captionTracks.find((t) => !this.isTrackAutoGenerated(t)) || null;
        }

        // 4. Ultimate fallback to the default first track
        if (!track) {
            track = captionTracks[0] || null;
        }

        return track;
    }

    private static isTrackAutoGenerated(track: CaptionTrack): boolean {
        return !!(track.kind === 'asr' || (track.vssId && track.vssId.startsWith('a.')));
    }

    /**
     * Parses the transcript XML string into raw SubtitleCue structures.
     */
    private static parseXmlToCues(xmlText: string, isAutoGenerated: boolean): SubtitleCue[] {
        const parser = new DOMParser();
        const xmlDoc = parser.parseFromString(xmlText, "text/xml");
        const textNodes = xmlDoc.getElementsByTagName('text');
        const cues: SubtitleCue[] = [];

        for (let i = 0; i < textNodes.length; i++) {
            const node = textNodes[i];
            const start = parseFloat(node.getAttribute('start') || '0');
            const duration = parseFloat(node.getAttribute('dur') || '0');
            const text = node.textContent || '';
            let cleanText = this.cleanSubtitleText(text);

            if (isAutoGenerated) {
                const lines = cleanText.split('\n');
                if (lines.length > 2) {
                    cleanText = lines.slice(-2).join('\n');
                }
            }

            if (cleanText) {
                cues.push({ start, duration, text: cleanText });
            }
        }
        return cues;
    }

    /**
     * Pure algorithm to de-flicker, de-duplicate, and smooth consecutive subtitle cues.
     * Makes writing unit tests and verification deterministic and simple.
     */
    private static mergeAndCleanCues(cues: SubtitleCue[], isAutoGenerated: boolean): SubtitleCue[] {
        const mergedCues: SubtitleCue[] = [];

        for (const cue of cues) {
            if (mergedCues.length === 0) {
                mergedCues.push({ ...cue });
                continue;
            }

            const lastCue = mergedCues[mergedCues.length - 1];
            const isDuplicate = Math.abs(lastCue.start - cue.start) < 0.1;

            // Prevent overlapping cues causing flicker on auto-generated transcripts.
            if (isAutoGenerated && !isDuplicate && cue.start < lastCue.start + lastCue.duration) {
                lastCue.duration = Math.max(0, cue.start - lastCue.start);
            }

            const gap = cue.start - (lastCue.start + lastCue.duration);
            const isPunctuation = /[.!?]$/.test(lastCue.text.trim());
            const shouldMerge = (!isAutoGenerated && gap >= 0 && gap < 1.0 && !isPunctuation && lastCue.text.length < 100);

            const normLast = lastCue.text.replace(/[.,!?¿¡\n]/g, '').toLowerCase().trim();
            const normClean = cue.text.replace(/[.,!?¿¡\n]/g, '').toLowerCase().trim();

            // Handle redundant content in subsequent cues
            if (normClean.startsWith(normLast) && normClean.length >= normLast.length) {
                lastCue.text = cue.text;
                lastCue.duration = Math.max(lastCue.duration, (cue.start + cue.duration) - lastCue.start);
                continue;
            }

            if (isDuplicate) {
                if (isAutoGenerated) {
                    lastCue.text = cue.text;
                } else if (!lastCue.text.toLowerCase().includes(cue.text.toLowerCase())) {
                    lastCue.text += (cue.text.startsWith('\n') ? '' : '\n') + cue.text;
                }
                lastCue.duration = Math.max(lastCue.duration, cue.duration);
                continue;
            }

            if (shouldMerge) {
                const lastWord = lastCue.text.split(' ').pop() || '';
                const firstWord = cue.text.split(' ')[0] || '';
                if (lastWord.toLowerCase() === firstWord.toLowerCase()) {
                    lastCue.text += ' ' + cue.text.substring(firstWord.length).trim();
                } else {
                    lastCue.text += (cue.text.startsWith('\n') ? '' : ' ') + cue.text;
                }
                lastCue.duration = Math.max(lastCue.duration, (cue.start + cue.duration) - lastCue.start);
                continue;
            }

            mergedCues.push({ ...cue });
        }

        mergedCues.sort((a, b) => a.start - b.start);
        return mergedCues;
    }
}
