export interface SubtitleCue {
    start: number;
    duration: number;
    text: string;
}

export interface CaptionTrack {
    baseUrl: string;
    kind?: string;
    vssId?: string;
    languageCode: string;
    name?: {
        simpleText?: string;
    };
}

export class YouTubeTranscriptFetcher {
    static cleanSubtitleText(text: string): string {
        return text.replace(/([a-zA-Z-áéíóúÁÉÍÓÚñÑ]+\s*)?\((auto-generated|generado automáticamente)\)/gi, '')
            .replace(/click[\s\S]*?for[\s\S]*?settings/gi, '')
            .replace(/haz\s*clic\s*para\s*ver\s*las\s*opciones/gi, '')
            .replace(/\[.*?\]/g, '')
            .replace(/\(.*?\)/g, '')
            .trim();
    }

    static async fetchTranscript(videoId: string, preferredLang: string = 'Auto'): Promise<SubtitleCue[]> {
        try {
            const response = await fetch(`https://www.youtube.com/watch?v=${videoId}`);
            const html = await response.text();

            const startStr = 'ytInitialPlayerResponse = ';
            const startIdx = html.indexOf(startStr);
            if (startIdx === -1) return [];
            const start = html.indexOf('{', startIdx);
            if (start === -1) return [];

            let braceCount = 0;
            let endIdx = -1;
            for (let i = start; i < html.length; i++) {
                if (html[i] === '{') braceCount++;
                else if (html[i] === '}') braceCount--;
                if (braceCount === 0) {
                    endIdx = i;
                    break;
                }
            }
            if (endIdx === -1) return [];

            const jsonStr = html.substring(start, endIdx + 1);
            const playerResponse = JSON.parse(jsonStr);
            const captionTracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks as CaptionTrack[] | undefined;
            if (!captionTracks || captionTracks.length === 0) return [];

            const lowerPref = preferredLang.toLowerCase();
            let track: CaptionTrack | null = null;

            if (preferredLang !== 'Auto') {
                const matchesPref = (t: CaptionTrack) =>
                    !!(t.name?.simpleText?.toLowerCase().includes(lowerPref) ||
                       t.languageCode.toLowerCase() === lowerPref.substring(0, 2));
                track = captionTracks.find((t: CaptionTrack) => matchesPref(t) && t.kind !== 'asr' && !t.vssId?.startsWith('a.')) || null;
                if (!track) {
                    track = captionTracks.find((t: CaptionTrack) => matchesPref(t)) || null;
                }
            }

            // Fallback to any manual track, then default track
            if (!track) {
                track = captionTracks.find((t: CaptionTrack) => t.kind !== 'asr' && !t.vssId?.startsWith('a.')) || null;
            }
            if (!track) {
                track = captionTracks[0] || null;
            }

            if (!track || !track.baseUrl) return [];
            const isAutoGenerated = !!(track.kind === 'asr' || (track.vssId && track.vssId.startsWith('a.')));

            const trackResponse = await fetch(track.baseUrl);
            const xmlText = await trackResponse.text();
            const parser = new DOMParser();
            const xmlDoc = parser.parseFromString(xmlText, "text/xml");
            const textNodes = xmlDoc.getElementsByTagName('text');
            const cues: SubtitleCue[] = [];

            for (let i = 0; i < textNodes.length; i++) {
                const node = textNodes[i];
                const startAttr = parseFloat(node.getAttribute('start') || '0');
                const durAttr = parseFloat(node.getAttribute('dur') || '0');
                const text = node.textContent || '';
                let cleanText = this.cleanSubtitleText(text);

                if (isAutoGenerated) {
                    const lines = cleanText.split('\n');
                    if (lines.length > 2) {
                        cleanText = lines.slice(-2).join('\n');
                    }
                }

                if (cleanText) {
                    const lastCue = cues.length > 0 ? cues[cues.length - 1] : null;
                    if (lastCue) {
                        const isDuplicate = Math.abs(lastCue.start - startAttr) < 0.1;

                        // For auto-generated, prevent overlapping cues which cause flicker.
                        if (isAutoGenerated && !isDuplicate && startAttr < lastCue.start + lastCue.duration) {
                            lastCue.duration = Math.max(0, startAttr - lastCue.start);
                        }

                        const gap = startAttr - (lastCue.start + lastCue.duration);
                        const isPunctuation = /[.!?]$/.test(lastCue.text.trim());
                        const shouldMerge = (!isAutoGenerated && gap >= 0 && gap < 1.0 && !isPunctuation && lastCue.text.length < 100);
                        const normLast = lastCue.text.replace(/[.,!?¿¡\n]/g, '').toLowerCase().trim();
                        const normClean = cleanText.replace(/[.,!?¿¡\n]/g, '').toLowerCase().trim();

                        if (normClean.startsWith(normLast) && normClean.length >= normLast.length) {
                            lastCue.text = cleanText;
                            lastCue.duration = Math.max(lastCue.duration, (startAttr + durAttr) - lastCue.start);
                            continue;
                        }
                        if (isDuplicate) {
                            if (isAutoGenerated) {
                                lastCue.text = cleanText;
                            } else if (!lastCue.text.toLowerCase().includes(cleanText.toLowerCase())) {
                                lastCue.text += (cleanText.startsWith('\n') ? '' : '\n') + cleanText;
                            }
                            lastCue.duration = Math.max(lastCue.duration, durAttr);
                            continue;
                        }
                        if (shouldMerge) {
                            const lastWord = lastCue.text.split(' ').pop() || '';
                            const firstWord = cleanText.split(' ')[0] || '';
                            if (lastWord.toLowerCase() === firstWord.toLowerCase()) {
                                lastCue.text += ' ' + cleanText.substring(firstWord.length).trim();
                            } else {
                                lastCue.text += (cleanText.startsWith('\n') ? '' : ' ') + cleanText;
                            }
                            lastCue.duration = Math.max(lastCue.duration, (startAttr + durAttr) - lastCue.start);
                            continue;
                        }
                    }
                    cues.push({ start: startAttr, duration: durAttr, text: cleanText });
                }
            }
            cues.sort((a, b) => a.start - b.start);
            return cues;
        } catch (error) {
            console.error('Failed to fetch YouTube transcript:', error);
            return [];
        }
    }
}
